### ISSUE TITLE
[1.19.2] Durability Loss on Hammer and excavators?

### ISSUE THREAD

**Issue by Daihok41** [kwpugh/easy_emerald_forge#13]
Is there any way to make it so the durability loss on hammers and excavators use 1 durability per block mined or dug up? I noticed it only uses 2 durability even when 9 blocks are mined or dug.

**Comment by kwpugh** [comment]
I tried as well and it does two durability.  Very odd.  I do not actually explicitly code damage.  The hammer simple extends the vanilla pickaxe and takes the damage when a block is broken.   the surrounding blocks are tested/broken after the target block is broken.  I will take a look at why two occur.

**Comment by kwpugh** [comment]
Looking through the  code, I see what I did wrong.  It had to do with the return statement of the canMine() method.  I will push and update today.  It was the same issue on the excavators.

**Comment by kwpugh** [comment]
Fixed in update.

**Comment by Daihok41** [comment]
Just tryed the update is there no way to make it so that it actually uses durability for each block mined or dug? Cause now they only use 1 durability even though you mine 9 blocks? just seems cheaty. I am not sure if you know what i mean .

**Comment by kwpugh** [comment]
I understand what you mean.  I have always had my area breaking tools only take one durability.   Recently, in the fabric versions of the mod I added a config option for take durability based upon number of blocks broken.  I may add that to the forge versions at some point.

I never agreed with the idea of taking 9 durability because it broke 9 blocks, I think it would take one durability because a hammer is a much larger tool than a pickaxe.  However, I understand some folks can't get past that idea.

**Comment by kwpugh** [comment]
v1.4.11 will have a config option for hammer and excavator to take full damage

**Comment by Daihok41** [comment]
Huge thanks man I really appreciate the new update and I do love the mod by the way makes things simple and not OP like some of the other mods, Very vanillish IMO.
