### ISSUE TITLE
Stone 

### ISSUE THREAD

**Issue by TheGabo56** [kwpugh/easy_emerald_forge#39]
Hello, I like very much this mod but i noticed that there is no paxel, hammer, excavator or tree axe for stone, i dont know if this is intentionally but i wonder if you can solve this thank you

**Comment by kwpugh** [comment]
hi.  that was intentional.  stone tools are too cheap.

**Comment by mpustovoi** [comment]
So I wonder why do wooden ones exist then? They are even cheaper.
In addition, wooden tools are hardly used, with the exception of a wooden pickaxe to get three cobblestones. Thus, special wooden tools are hardly needed.

**Comment by kwpugh** [comment]
I use wooden hammers, excavators, and tree axes until I get copper or iron.  Getting wood does require some work, depending on your location, but stone would always be too easy.

**Comment by mpustovoi** [comment]
And this is because there are no stone analogues :)
Stone is still nothing if there is no wood. For instance, when spawning either in the mountains, or on an island without trees, or in an icy biome.
After all, it is easier to renew a wood rather than a stone in the early stages of the game. And in the later stages, the stone is no longer needed. Well, this is already far-fetched point.
The only thing that I think is really op in stone tools is an axe with 9 damage like a diamond one. Otherwise, everything is in balance with the progression of "wood to stone to iron".

**Comment by mpustovoi** [comment]
I agree with you that after going through many caves, you will most likely have a lot more stone than wood.
Although then you will probably have more iron.

**Comment by kwpugh** [comment]
I wanted to avoid the situation of players going underground with a couple of stacks of sticks and being able to making a huge number of stone hammers to mine for days.  I think it is a little more challenging to NOT have the stone hammer/excavator, making do with wood until copper or iron.  These days, copper is so abundant in the world, getting to copper hammers is pretty quick anyway.

I originally, was only going to have the extra tools for iron & diamond, but added wood as a starter material.

First day in a game I generally make a wooden treeaxe and load up on logs before finding an underground shelter.

**Comment by mpustovoi** [comment]
Fair.
Oh yes, I completely forgot about the copper, which is just tons around.
