### ISSUE TITLE
[1.21] Error on launch. Not sure what it could be.

### ISSUE THREAD

**Issue by OneShot313** [kwpugh/easy_emerald_forge#42]
![Error](https://github.com/user-attachments/assets/148d09ac-ce4e-4473-8d00-4cba23d626c9)

Not sure why this occurs. I'm using 1.21 Neoforge 21.0.83-beta.

**Comment by J-K-X** [comment]
Same problem here any solutions?
~(using the latest release being neoforge-1.6.28)

**Comment by kwpugh** [comment]
cannot use NeoForge later than 21.0.81.
Neoforge made changes to their config system that broke many of my mods.
Update is in the works.

**Comment by kwpugh** [comment]
A refactor in NeoForge 21.0.82 closed off an option to load my config file without using FML.  I was doing this to load my config values before items and such were registered so that I would have those values to use during registering.   This allowed players to adjust tool and armor material values and many other things.  NeoForge forces the config to be loaded AFTER registering items and such, precluding the use of player-supplied values.

As such, I've decided to leverage my custom config system from my fabric mods in NeoForge.  This will restore full functionality.

Bottomline:  using any of my NeoForge mods on NeoForge 21.0.82+ will crash at present.  It will take me a few days to get everything converted.

**Comment by kwpugh** [comment]
Issued fixed with latest release of EasyEmeralds
